In [7]:
import numpy as np
A = np.array(
 [[4, -5, 7],
 [1, -4, 9],
 [-4, 0, 5],
 ]
 )
At = np.transpose(A)
print("Базова матриця A:")
print(A)
print(f"Визначник базової матриці А: {int(np.linalg.det(A))}")
print("Транспонована матриця At:")
print(At)
print(f"Визначник транспонованої матриці At: {int(np.linalg.det(A))}")

# Базова матриця A:
# [[ 4 -5 7]
#  [ 1 -4 9]
#  [-4 0 5]]
# Визначник базової матриці А: 12
# Транспонована матриця At:
# [[ 4 1 -4]
#  [-5 -4 0]
#  [ 7 9 5]]
# Визначник транспонованої матриці At: 1

Базова матриця A:
[[ 4 -5  7]
 [ 1 -4  9]
 [-4  0  5]]
Визначник базової матриці А: 12
Транспонована матриця At:
[[ 4  1 -4]
 [-5 -4  0]
 [ 7  9  5]]
Визначник транспонованої матриці At: 12
